const data = [
    {"filename":"PagesController#index",
    "name":"Home",
    "heading":"",
    "lang":"en",
    "ID":"84",
    "content":"",
    "link":"\/",
    "TemplateParametars":null,
    "MediaFilePath":"media\/pages\/",
    "FileName":null,
    "SEO_title":"",
    "SEO_metaDescription":"",
    "SEO_metaKeywords":"",
    "template":"PagesController#index",
    "latest":[
        {"ID":"2557025",
        "link":"how-about-some-truffles-from-around-zagreb",
        "naslov":"How about Some Truffles from around Zagreb?",
        "heading":"Zagreb has been known for a number of things, but truffles are definitely not one of them. Yet, surprisingly enough, this might change in future.",
        "Likes":"207",
        "CustomFieldsValues":{"Autor":""},
        "datum_od":"30.10.2020",
        "PagesLink":"\/topics\/gastro",
        "TopicName":"Gastro",
        "Liked":null,
        "MediaFilePath":"media\/news\/",
        "FileName":"naslovna@a6e4a2b9-2d78-44be-8611-543030707e3e.jpg"},
        {"ID":"2557009","link":"ag-matos-a-poet-modernist-and-beloved-zagrebian",
        "naslov":"A.G. Mato\u0161 \u2013 A Poet, Modernist And Beloved Zagrebian",
        "heading":"\"Considered to be the champion of Croatian modernist literature, one of the greatest merits attributed to Mato\u0161 is opening up Croatian literature to modern European literature and the currents of his time.\"",
        "Likes":"227",
        "CustomFieldsValues":{"Autor":""},
        "datum_od":"29.10.2020",
        "PagesLink":"\/topics\/more-than-words",
        "TopicName":"More than Words",
        "Liked":null,
        "MediaFilePath":"media\/news\/",
        "FileName":"matos@a9502090-4453-404d-ad48-880a688733bb.jpg"},
        {"ID":"2557019","link":"zagrebtrivia-zagreb-forests",
        "naslov":"#ZagrebTrivia - Zagreb Forests",
        "heading":"Forests make up a third of #Zagreb. These green oases are perfect for a recreation... It is time to rediscover them!",
        "Likes":"285",
        "CustomFieldsValues":{"Autor":""},
        "datum_od":"22.10.2020",
        "PagesLink":"\/zagrebvlog\/zagrebtrivia",
        "TopicName":"ZagrebTrivia",
        "Liked":null,
        "MediaFilePath":"media\/news\/",
        "FileName":"heading@fbd0a755-3513-4fe3-ad88-7cc38ee784cf.jpg"},
        {"ID":"2557007","link":"an-ode-to-croatian-parlour-music-we-finally-know-whos-the-stranger-in-the-night",
        "naslov":"An Ode To Croatian Parlour Music: We Finally Know Who's The Stranger In The Night",
        "heading":"My favorite song about Zagreb is precisely his song, \"Golubovi,\" meaning simply \"pigeons.\" In this song, he describes them as: \"The most beautiful roses above my town...\".",
        "Likes":"231",
        "CustomFieldsValues":{"Autor":""},
        "datum_od":"21.10.2020",
        "PagesLink":"\/topics\/more-than-words",
        "TopicName":"More than Words",
        "Liked":null,
        "MediaFilePath":"media\/news\/",
        "FileName":"gradske-subota-11042020-39@ce5a3ff9-1b25-4746-94a0-a2e7e303d650.jpg"},
        {"ID":"2557017",
        "link":"young-wine-for-cold-days",
        "naslov":"Young Wine for Cold Days",
        "heading":"The French have to wait until the third Thursday in November for their world-famous young wine called Beaujolais nouveau to come out and fill the glasses of eager wine lovers. Luckily, the citizens of Zagreb and its surroundings can enjoy their own delicious young wine much sooner.",
        "Likes":"259",
        "CustomFieldsValues":{"Autor":""},
        "datum_od":"15.10.2020",
        "PagesLink":"\/topics\/gastro",
        "TopicName":"Gastro",
        "Liked":null,
        "MediaFilePath":"media\/news\/",
        "FileName":"naslovna@51577527-f586-4620-bfef-d3c52babc490.jpg"},
        {"ID":"2557013",
        "link":"zagreb-locals",
        "naslov":"Zagreb Locals: A Young Entrepreneur With A Unique Idea",
        "heading":"Leo is a 17-year old Zagrebian who has already started his own successful business. What is it like to start a business at a such young age? How does he balance school and work-life and what does he do to unwind in his free time? Find out in our interview.",
        "Likes":"253",
        "CustomFieldsValues":{"Autor":""},
        "datum_od":"08.10.2020",
        "PagesLink":"\/topics\/more-than-words",
        "TopicName":"More than Words",
        "Liked":null,
        "MediaFilePath":"media\/news\/",
        "FileName":"thumbnail-dji-0030@314747d2-58b7-4ab5-940d-9c2e54340b6b.jpg"},
        {"ID":"2557016",
        "link":"a-tale-of-two-ivanas",
        "naslov":"A Tale of Two Ivanas",
        "heading":"Zagreb's food scene is as lively as ever \u2013 some brave and visionary people obviously see a window of opportunity in this wretched year.",
        "Likes":"203",
        "CustomFieldsValues":{"Autor":""},
        "datum_od":"02.10.2020",
        "PagesLink":"\/topics\/gastro",
        "TopicName":"Gastro",
        "Liked":null,"MediaFilePath":"media\/news\/",
        "FileName":"naslovna@ae30fd4d-0141-448c-911b-c45e9dd464b5.jpg"},
        {"ID":"2557004",
        "link":"-en-5f48b100198d8",
        "naslov":"Zagreb Locals: The Art of Shoemaking as It Once Was",
        "heading":"There is something really special about a family business that has been around for 80 years and three generations. Zagrebian shoemaking store Cipele Igrec is precisely that. Find out more in our monthly Zagreb locals interview.",
        "Likes":"208",
        "CustomFieldsValues":{"Autor":""},
        "datum_od":"25.09.2020",
        "PagesLink":"\/topics\/more-than-words",
        "TopicName":"More than Words",
        "Liked":null,"MediaFilePath":"media\/news\/",
        "FileName":"42254109-604637333266570-8427512226084028416-o@80284d08-b070-463c-8d6d-d5cbec0558e2.jpg"}
    ],
    "topics":[{"ID":"196","isDropdown":"1","link":"\/topics\/gastro","hreflink":"","name":"Gastro","ClassName":"","UseHash":"0","clickable":"1","ima":"0","FileName":null,"MediaFilePath":null,"article":{"ID":"2557025","IDKat":"196","naslov":"How about Some Truffles from around Zagreb?","link":"how-about-some-truffles-from-around-zagreb","heading":"Zagreb has been known for a number of things, but truffles are definitely not one of them. Yet, surprisingly enough, this might change in future.","FileName":"naslovna@a6e4a2b9-2d78-44be-8611-543030707e3e.jpg","PagesLink":"\/topics\/gastro","TopicName":"Gastro","datum_od":"30.10.2020","MediaFilePath":"media\/news\/","Likes":"207","Liked":null}},{"ID":"198","isDropdown":"1","link":"\/topics\/become-a-zagrebian","hreflink":"","name":"Become a Zagrebian","ClassName":"","UseHash":"0","clickable":"1","ima":"0","FileName":null,"MediaFilePath":null,"article":{"ID":"2556964","IDKat":"198","naslov":"Mateo: An Unofficial Triathlete","link":"mateo-an-unofficial-triathletehello-world-my-name-is-mateo-im-25-im-kind-of-a-sports-addict-and-zagreb-is-my-town-i-was-born-and-raised-here-and-i-hope-that-some-day-this-will-be-my-childrens-town-to-i-love-my-home-town-because-it-offers-you-so-many-thing","heading":"Mateo is a true sports enthusiast, and if you're one, also, he's giving you an opportunity to see Zagreb through his eyes: \"Running, cycling, swimming, and mountain climbing. Those are my favorite sports, and Zagreb gives you the opportunities to try your best at all of them.\"","FileName":"d5d69b25-1a21-4812-8a5c-2bd20f331691.jpg","PagesLink":"\/topics\/become-a-zagrebian","TopicName":"Become a Zagrebian","datum_od":"25.05.2020","MediaFilePath":"media\/news\/","Likes":"219","Liked":null}},{"ID":"195","isDropdown":"1","link":"\/topics\/more-than-words","hreflink":"","name":"More than Words","ClassName":"","UseHash":"0","clickable":"1","ima":"0","FileName":null,"MediaFilePath":null,"article":{"ID":"2557009","IDKat":"195","naslov":"A.G. Mato\u0161 \u2013 A Poet, Modernist And Beloved Zagrebian","link":"ag-matos-a-poet-modernist-and-beloved-zagrebian","heading":"\"Considered to be the champion of Croatian modernist literature, one of the greatest merits attributed to Mato\u0161 is opening up Croatian literature to modern European literature and the currents of his time.\"","FileName":"matos@a9502090-4453-404d-ad48-880a688733bb.jpg","PagesLink":"\/topics\/more-than-words","TopicName":"More than Words","datum_od":"29.10.2020","MediaFilePath":"media\/news\/","Likes":"227","Liked":null}},
    {"ID":"190","isDropdown":"1","link":"\/topics\/seasonal-zagreb","hreflink":"","name":"Seasonal Zagreb","ClassName":"","UseHash":"0","clickable":"1","ima":"0","FileName":null,"MediaFilePath":null,"article":{"ID":"2556986","IDKat":"190","naslov":"June in Zagreb: Let's Enjoy Our City Again","link":"june-in-zagreb-lets-enjoy-in-our-city-again","heading":"As we're getting back to a normal way of life, you may want to head out and explore Zagreb museums, galleries, upcoming concerts, and theatres. I've created a list of a couple of interesting ones for this June. Enjoy it.","FileName":"zrinjevac-park-2-j-duval-592bede468d09@4729e0b5-bafd-4afb-81fd-1a9b3286561c.jpg","PagesLink":"\/topics\/seasonal-zagreb","TopicName":"Seasonal Zagreb","datum_od":"27.05.2020","MediaFilePath":"media\/news\/","Likes":"268","Liked":null}},{"ID":"191","isDropdown":"1","link":"\/topics\/something-to-look-forward-to","hreflink":"","name":"Something to Look Forward to","ClassName":"","UseHash":"0","clickable":"1","ima":"0","FileName":null,"MediaFilePath":null,"article":{"ID":"2557002","IDKat":"191","naslov":"When the Longest Street in Zagreb Comes to Life - Q'Art: Project Ilica","link":"qart-project-ilica","heading":"It was 20 years ago that Aleksandar Battista Ili\u0107 initiated the Community Art Project and the Ilica project along with it. From the very beginnings, the emphasis was on socially engaged art forms in the community.","FileName":"img-2208@9c0856fb-75b2-4889-a0de-14beaed7775f.jpg","PagesLink":"\/topics\/something-to-look-forward-to","TopicName":"Something to Look Forward to","datum_od":"08.09.2020","MediaFilePath":"media\/news\/","Likes":"239","Liked":null}},{"ID":"192","isDropdown":"1","link":"\/topics\/neighbors-guide","hreflink":"","name":"Neighbor's Guide","ClassName":"","UseHash":"0","clickable":"1","ima":"0","FileName":null,"MediaFilePath":null,"article":{"ID":"2556991","IDKat":"192","naslov":"Looking in Other Types of Sightseeing: Zagreb From Above","link":"looking-down-on-other-types-of-sightseeing-zagreb-from-above","heading":"We'll probably never fly exactly like birds, but I think it's safe to say that these means of traveling skies are also amazing, if not better. Wouldn't you agree?","FileName":"boris-frkovic@3d9ef997-2b74-4669-bb90-6820c083bee4.jpg","PagesLink":"\/topics\/neighbors-guide","TopicName":"Neighbor's Guide","datum_od":"28.07.2020","MediaFilePath":"media\/news\/","Likes":"221","Liked":null}},{"ID":"193","isDropdown":"1","link":"\/topics\/zagreb-for-kids","hreflink":"","name":"Zagreb for Kids","ClassName":"","UseHash":"0","clickable":"1","ima":"0","FileName":null,"MediaFilePath":null,"article":{"ID":"2556960","IDKat":"193","naslov":"Fa\u0161nik: The Favorite Croatian Custom of the Little Ones","link":"fasnik-the-favorite-croatian-custom-of-the-little-ones","heading":"An old Croatian custom from the 19th century, and a political satire to do the afore-described show. The main characters are the Fa\u0161nik prince, princess Magpie, The Judge, and the lawyer who are taking over the city keys for the day, commenting on the current political events and social topics, and have a real blast out of it all.","FileName":"80a31890-8fc8-4541-bfa2-36b545fc2dbc.jpg","PagesLink":"\/topics\/zagreb-for-kids","TopicName":"Zagreb for Kids","datum_od":"13.02.2020","MediaFilePath":"media\/news\/","Likes":"243","Liked":null}},{"ID":"194","isDropdown":"1","link":"\/topics\/heartbeat-of-zagreb","hreflink":"","name":"Heartbeat of Zagreb","ClassName":"","UseHash":"0","clickable":"1","ima":"0","FileName":null,"MediaFilePath":null,"article":{"ID":"2556995","IDKat":"194","naslov":"The Last Video Store in Zagreb: More Than Just A Place To Rent A Movie","link":"video-stores-the-dinosaurs-of-home-entertainment","heading":"Probably the most valuable thing about the video store is the advice given by the owner, Marko Jantol. He is a real film encyclopedia with a great ability to evaluate people's movie tastes.","FileName":"107569360-3171371862946299-8273985183121712420-n@d81f7670-44e6-4c46-8abf-908130e7cec6.jpg","PagesLink":"\/topics\/heartbeat-of-zagreb","TopicName":"Heartbeat of Zagreb","datum_od":"21.08.2020","MediaFilePath":"media\/news\/","Likes":"266","Liked":null}}],"mostLiked":[{"ID":"2556931","link":"cevapi-the-visitors-that-came-to-stay","PagesLink":"\/topics\/gastro","naslov":"\u0106evapi \u2013 The Visitors That Came to Stay","heading":"\u0106evapi are the most famous representative of the Balkan grill genre, a dish that entered south-eastern Europe during the Ottoman period. Their origin is oriental, deriving from the Turkish kebab.","DateCreated":"2019-11-28 14:05:28","datum_od":"28.11.2019","IDKat":"196","CustomFieldsValues":{"Autor":""},"Likes":"303","MediaFilePath":"media\/news\/","FileName":"ac18dbcc-9828-4b7e-af3d-417055e89263.jpg","TopicName":"Gastro"},{"ID":"2556891","link":"zagreb-college-guide","PagesLink":"\/topics\/neighbors-guide","naslov":"Zagreb University - A Student Guide Through the City","heading":"The old saying goes: \"The student days are the most beautiful ones.\" And, the Zagreb is a city which confirms that popular opinion.","DateCreated":"2019-08-20 15:30:28","datum_od":"26.09.2019","IDKat":"192","CustomFieldsValues":{"Autor":""},"Likes":"300","MediaFilePath":"media\/news\/","FileName":"national-and-university-library-j-duval-592bec79f273b@2556891@5d665f4cb1fd3.jpg","TopicName":"Neighbor's Guide"},{"ID":"2556981","link":"sunday-roast-in-good-times-and-in-bad-times","PagesLink":"\/topics\/gastro","naslov":"Sunday Roast \u2013 In Good Times and in Bad Times","heading":"One of my fondest childhood memories when it comes to food is our typical Sunday family lunch. In 99% of the cases it was the same dish, but I never got bored of it \u2013 roast chicken and potatoes, lettuce salad on the side.","DateCreated":"2020-05-01 17:00:54","datum_od":"13.04.2020","IDKat":"196","CustomFieldsValues":{"Autor":""},"Likes":"299","MediaFilePath":"media\/news\/","FileName":"naslovna@98501467-0e16-4d32-9bc7-2261b65034ee.jpg","TopicName":"Gastro"},{"ID":"2556981","link":"sunday-roast-in-good-times-and-in-bad-times","PagesLink":"\/infozagreb-sto-raditi-kod-kuce","naslov":"Sunday Roast \u2013 In Good Times and in Bad Times","heading":"One of my fondest childhood memories when it comes to food is our typical Sunday family lunch. In 99% of the cases it was the same dish, but I never got bored of it \u2013 roast chicken and potatoes, lettuce salad on the side.","DateCreated":"2020-05-01 17:00:54","datum_od":"13.04.2020","IDKat":"213","CustomFieldsValues":{"Autor":""},"Likes":"299","MediaFilePath":"media\/news\/","FileName":"naslovna@98501467-0e16-4d32-9bc7-2261b65034ee.jpg","TopicName":"Infozagreb - \u0160to raditi kod ku\u0107e"},{"ID":"2556837","link":"tourists-of-zagreb-mixing-business-and-pleasure-in-zagreb","PagesLink":"\/topics\/more-than-words","naslov":"Tourists of Zagreb: An Undiscovered Gem","heading":"If you're planning a city break in Zagreb, read our interview with Caitlin from NYC and get an idea of where to go and what to do.","DateCreated":"2019-03-28 13:09:26","datum_od":"25.04.2019","IDKat":"195","CustomFieldsValues":{"Autor":""},"Likes":"298","MediaFilePath":"media\/news\/","FileName":"media5cc6fa54a0a91@2556837@5cc6fa54c2391.jpg","TopicName":"More than Words"},{"ID":"2556351","link":"passage-to-happiness-56572a2ec7c51","PagesLink":"\/topics\/more-than-words","naslov":"Passage to Happiness","heading":"Sometimes, when you just browse around, you suddenly feel a rush of love towards the city. To put yourself into this mode and mood, you just need to get lost a little...","DateCreated":"2015-11-11 16:30:36","datum_od":"27.11.2015","IDKat":"195","CustomFieldsValues":{"Autor":""},"Likes":"297","MediaFilePath":"media\/news\/","FileName":"oktogonpassage4mvrdoljak-564367ccc3372.jpg","TopicName":"More than Words"}],"loops":[{"ID":"2557027","IDKat":"210","naslov":"Gradec - izvan okvira","link":"gradec-izvan-okvira","heading":"","FileName":"gradec-izvan-okvira@784b70a1-fa21-4288-8092-57191ef864f9.mp4","PagesLink":"\/zagrebloop","TopicName":"ZagrebLoop","datum_od":"11.11.2020","MediaFilePath":"media\/news\/","Likes":"229","Liked":null},{"ID":"2557026","IDKat":"210","naslov":"Otkucaj srca","link":"otkucaj-srca","heading":"","FileName":"otkucaj-srca@1f1fe631-7c71-4b4d-94d3-71bd2e82f591.mp4","PagesLink":"\/zagrebloop","TopicName":"ZagrebLoop","datum_od":"04.11.2020","MediaFilePath":"media\/news\/","Likes":"230","Liked":null},{"ID":"2557024","IDKat":"210","naslov":"Mural Marti\u0107eva Vojnovi\u0107eva","link":"mural-marticeva-vojnoviceva","heading":"","FileName":"mural-marticeva-vojnoviceva-zgloop@32147f72-673f-4754-9a64-2c16b0caee86.mp4","PagesLink":"\/zagrebloop","TopicName":"ZagrebLoop","datum_od":"23.10.2020","MediaFilePath":"media\/news\/","Likes":"208","Liked":null},{"ID":"2557015","IDKat":"210","naslov":"The Spring of Life","link":"the-spring-of-life","heading":"","FileName":"zdenac-zivota-zagreb-loop@6e9f56dd-9858-4b73-a30c-a18d92e6ccfb.mp4","PagesLink":"\/zagrebloop","TopicName":"ZagrebLoop","datum_od":"23.09.2020","MediaFilePath":"media\/news\/","Likes":"272","Liked":null}],
    "latestImages":[{"MediaID":"947297","ForeignType":"5","ForeignID":"1","MediaGroup":"gallery","FileName":"vjesnik@1@5e99c54d14660.jpg","MediaType":"IMAGE","ExternalLink":null,"OrderNum":"0","Active":"1","Description":"Inga Sternak","Tags":null,"Published":"1","DateAdded":null,"DateUpdated":null},{"MediaID":"946747","ForeignType":"5","ForeignID":"1","MediaGroup":"gallery","FileName":"wp-20190822-06-46-16-pro@1@5da378d706f09.jpg","MediaType":"IMAGE","ExternalLink":null,"OrderNum":"0","Active":"1","Description":"Dino Hrvat","Tags":null,"Published":"1","DateAdded":null,"DateUpdated":null},{"MediaID":"946685","ForeignType":"5","ForeignID":"1","MediaGroup":"gallery","FileName":"p9213003@1@5d8e217e8501a.JPG","MediaType":"IMAGE","ExternalLink":null,"OrderNum":"0","Active":"1","Description":"Sandra","Tags":null,"Published":"1","DateAdded":null,"DateUpdated":null},{"MediaID":"946650","ForeignType":"5","ForeignID":"1","MediaGroup":"gallery","FileName":"-dsc5210@1@5d4ccd2ea5eee.jpg","MediaType":"IMAGE","ExternalLink":null,"OrderNum":"0","Active":"1","Description":"Cristi\u00e1n Escobar","Tags":null,"Published":"1","DateAdded":null,"DateUpdated":null},{"MediaID":"946608","ForeignType":"5","ForeignID":"1","MediaGroup":"gallery","FileName":"2aed642b-fd64-4e79-aa88-7c8a02ae3929@1@5cd914c548174.jpg","MediaType":"IMAGE","ExternalLink":null,"OrderNum":"0","Active":"1","Description":"Amine El Fahel","Tags":null,"Published":"1","DateAdded":null,"DateUpdated":null},{"MediaID":"946583","ForeignType":"5","ForeignID":"1","MediaGroup":"gallery","FileName":"stara-iara@1@5c80ec866a9fe.jpg","MediaType":"IMAGE","ExternalLink":null,"OrderNum":"0","Active":"1","Description":"Dalibor Platenik","Tags":null,"Published":"1","DateAdded":null,"DateUpdated":null},{"MediaID":"946571","ForeignType":"5","ForeignID":"1","MediaGroup":"gallery","FileName":"p4210797@1@5c770191cc8cc.JPG","MediaType":"IMAGE","ExternalLink":null,"OrderNum":"0","Active":"1","Description":"juraj jonke","Tags":null,"Published":"1","DateAdded":null,"DateUpdated":null},{"MediaID":"946567","ForeignType":"5","ForeignID":"1","MediaGroup":"gallery","FileName":"botaniki-vrt-zagreb@1@5c76ff8b5a343.JPG","MediaType":"IMAGE","ExternalLink":null,"OrderNum":"0","Active":"1","Description":"juraj jonke","Tags":null,"Published":"1","DateAdded":null,"DateUpdated":null}],"bodyClass":"index"}
]

export default data